CREATE TABLE IF NOT EXISTS Country(
                                      id bigint generated by default as identity primary key,
                                      name varchar(255),
                                      continent varchar(255)
);

CREATE TABLE IF NOT EXISTS Host(
                                   id bigint generated by default as identity primary key,
                                   name varchar(255),
                                   surname varchar(255),
                                   country_id bigint references Country
);

CREATE TABLE IF NOT EXISTS Accommodation(
                                            id bigint generated by default as identity primary key,
                                            name varchar(255),
                                            category varchar(50),
                                            host_id bigint references Host,
                                            numRooms int,
                                            is_rented boolean default false
);

CREATE TABLE IF NOT EXISTS App_user(
                                       username varchar(255) primary key,
                                       password varchar(255),
                                       name varchar(255),
                                       surname varchar(255),
                                       is_account_non_expired boolean default true,
                                       is_account_non_locked boolean default true,
                                       is_credentials_non_expired boolean default true,
                                       is_enabled boolean default true,
                                       role varchar(50)
);

CREATE TABLE IF NOT EXISTS TemporaryList(
                                            id bigint generated by default as identity primary key,
                                            user_id varchar(255) references App_user(username),
                                            accommodation_id bigint references Accommodation
);